v001

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -41,3 +41,7 @@ jobs:
     - name: Push Docker image
       run: |
         docker push ${{ secrets.DOCKERHUB_USERNAME }}/recommendation:latest
+
+    - name: Check Dockerfile
+      run: test -f Dockerfile || (echo "Dockerfile not found!" && exit 1)
+
